services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - mongo
    env_file:
      - backend/.env
    expose:
      - "3000"
    restart: unless-stopped
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped
      
volumes:
  mongo_data:
