services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/gestao-projetos
    expose:
      - "3000"
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
      
volumes:
  mongo_data:
