apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: henriquepina/proj3-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/gestao-projetos
              #value: mongodb://10.99.20.157:27017/gestao-projetos