# 1) ServiceAccount específico para o Prometheus
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: default

---
# 2) ClusterRole com as permissões de scrape necessárias
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-scrape
rules:
  # listar/watch/endpoints de pods e services
  - apiGroups: [""]
    resources: ["nodes","pods","services","endpoints","namespaces"]
    verbs: ["get","list","watch"]
  # deployments, replicasets, statefulsets...
  - apiGroups: ["apps","extensions"]
    resources: ["deployments","replicasets","statefulsets","daemonsets"]
    verbs: ["get","list","watch"]

---
# 3) Vincula o novo SA ao ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-scrape-binding
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: default
roleRef:
  kind: ClusterRole
  name: prometheus-scrape
  apiGroup: rbac.authorization.k8s.io
