{
 "title": "Dashboard de Aplicação",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Logs Frontend",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=~\"^/var/log/containers/frontend.*\"}"
    }
   ]
  },
  {
   "title": "Logs Backend",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=~\"^/var/log/containers/backend.*\"}"
    }
   ]
  },
  {
   "title": "Requisições por Método",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (method) (rate(http_request_duration_seconds_count{job=\"backend\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência Média por Rota",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"backend\"}[1m]) \r\n/ \r\nrate(http_request_duration_seconds_count{job=\"backend\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Erros HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (status_code) (increase(http_request_duration_seconds_count{job=\"backend\", status_code=~\"4..|5..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}