{
 "title": "Dashboard Teste",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Logs Frontend",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{filename=\"/var/log/containers/frontend-57bbc57bdb-4xw59_default_frontend-42f82aeb593601ed8c90c9b1e4fd2173b89a390810cc3b61a6f18b3dd3ab68ba.log\"} |= ``"
    }
   ]
  },
  {
   "title": "Logs Backend",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{filename=\"/var/log/containers/backend-dffb9c784-7ntkp_default_backend-841e7d410fa6777fdc559312cdc60ae83ab70806a3e5fc2a7137ba85ae58a022.log\"} |= ``"
    }
   ]
  },
  {
   "title": "Pods Rodando",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers Rodando",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU por Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(container_cpu_usage_seconds_total{container!=\"POD\",namespace=~\"$namespace\"}[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memória por Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  container_memory_usage_bytes{container!=\"POD\",namespace=~\"$namespace\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Erros HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (status_code) (increase(http_request_duration_seconds_count{job=\"backend\", status_code=~\"4..|5..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencia Média por Rota",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"backend\"}[1m]) \r\n/ \r\nrate(http_request_duration_seconds_count{job=\"backend\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requisições por Metodo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (method) (rate(http_request_duration_seconds_count{job=\"backend\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}